#!/bin/sh
chmod +x /etc/init.d/advancedplus
uci -q batch <<-EOF >/dev/null
	delete ucitrack.@advancedplus[-1]
	add ucitrack advancedplus
	set ucitrack.@advancedplus[-1].init=advancedplus
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
