#!/bin/sh /etc/rc.common
#  Copyright 2019-2023 sirpdboy <sirpdboy@qq.com>

START=95
STOP=15
EXTRA_COMMANDS='reset'
EXTRA_HELP="        reset   Reset to default settings"

reset() {
rm -rf /etc/config/advancedplus
cat <<EOF  >>/etc/config/advancedplus
    config basic
	option gossr 'bypass'
	option gouser 'admin'
	option gohome 'overview'
	option background '0'
	option mode 'light'
	option primary_rgbs '225,112,88'
	option primary_body '#f8f8f8'
	option primary '#2d6693'
	option primary_rgb '45,102,147'
	option primary_rgb_ts '0.3'
	option fontmode '0'
	option font_d '1.2rem'
	option font_z '0.92rem'
	option font_x '0.875rem'

config theme
	option primary_rgb '74,161,133'
	option primary_body '#f8f8f8'
	option primary_rgbs '38,12,6'
	option mode 'light'
	option primary 'green'
	option primary_rgb_ts '0.3'
	option use '1'

config theme
	option primary_body '#f8f8f8'
	option primary_rgbs '225,112,88'
	option primary '#2d6693'
	option primary_rgb '45,102,147'
	option mode 'light'
	option primary_rgb_ts '0.3'
	option use '0'

config theme
	option primary_body '#212d3c'
	option primary '#101f30'
	option primary_rgbs '38,12,6'
	option primary_rgb '133,95,3'
	option mode 'dark'
	option use '1'
	option primary_rgb_ts '0.5'

config theme
	option primary 'green'
	option primary_body '#f8f8f8'
	option primary_rgb '74,161,133'
	option primary_rgbs '225,112,88'
	option mode 'dark'
	option use '0'
	option primary_rgb_ts '0.3'
EOF
}


kucatset(){
sum=$(grep -c 'theme' /etc/config/advancedplus)
useset=0
for i in $(seq 0 $((sum-1)))
do
    use=$(uci -q get advancedplus.@theme[$i].use )
    
    if [ "x$use" = "x1" ]; then
	mode=`uci -q get advancedplus.@theme[$i].mode`
	primary=`uci -q get advancedplus.@theme[$i].primary`
	uci set advancedplus.@basic[0].mode=${mode}
	case "$primary" in
		blue)
			uci set advancedplus.@basic[0].primary='#146db3'
			uci set advancedplus.@basic[0].primary_rgb='20,109,179'
			uci set advancedplus.@basic[0].primary_rgb_ts=`uci -q get advancedplus.@theme[$i].primary_rgb_ts`
			uci set advancedplus.@basic[0].primary_rgbs='205,79,57'
 			[ $mode = dark ] && uci set advancedplus.@basic[0].primary_body='#212d3c' || uci set advancedplus.@basic[0].primary_body='#f8f8f8'
		;;
		green)
			uci set advancedplus.@basic[0].primary='#1a8361'
			uci set advancedplus.@basic[0].primary_rgb='26,131,97'
			uci set advancedplus.@basic[0].primary_rgb_ts=`uci -q get advancedplus.@theme[$i].primary_rgb_ts`
			uci set advancedplus.@basic[0].primary_rgbs='225,112,88'
 			[ $mode = dark ] && uci set advancedplus.@basic[0].primary_body='#212d3c' || uci set advancedplus.@basic[0].primary_body='#f8f8f8'
		;;
		orange)
		
			uci set advancedplus.@basic[0].primary='#a34706'
			uci set advancedplus.@basic[0].primary_rgb='163,71,6'
			uci set advancedplus.@basic[0].primary_rgb_ts=`uci -q get advancedplus.@theme[$i].primary_rgb_ts`
			uci set advancedplus.@basic[0].primary_rgbs='60,179,113'
 			[ $mode = dark ] && uci set advancedplus.@basic[0].primary_body='#212d3c' || uci set advancedplus.@basic[0].primary_body='#f8f8f8'
		;;
		red)
			uci set advancedplus.@basic[0].primary='#b3351f'
			uci set advancedplus.@basic[0].primary_rgb='143,32,13'
			uci set advancedplus.@basic[0].primary_rgb_ts=`uci -q get advancedplus.@theme[$i].primary_rgb_ts`
			uci set advancedplus.@basic[0].primary_rgbs='33,150,243'
 			[ $mode = dark ] && uci set advancedplus.@basic[0].primary_body='#212d3c' || uci set advancedplus.@basic[0].primary_body='#f8f8f8'
		;;
		*)
			uci set advancedplus.@basic[0].primary=`uci -q get advancedplus.@theme[$i].primary`
			uci set advancedplus.@basic[0].primary_rgb=`uci -q get advancedplus.@theme[$i].primary_rgb`
			uci set advancedplus.@basic[0].primary_rgbs=`uci -q get advancedplus.@theme[$i].primary_rgbs`
			uci set advancedplus.@basic[0].primary_rgb_ts=`uci -q get advancedplus.@theme[$i].primary_rgb_ts`
 			[ $mode = dark ] && uci set advancedplus.@basic[0].primary_body='#212d3c' || uci set advancedplus.@basic[0].primary_body='#f8f8f8'
 		;;
	esac
	useset=1
	break
    fi
done
if [ "x$useset" = "x0" ] ; then
	uci set advancedplus.@basic[0].mode='light'
	uci set advancedplus.@basic[0].primary='#4aa185'
	uci set advancedplus.@basic[0].primary_rgb='74,161,133'
	uci set advancedplus.@basic[0].primary_rgb_ts='0.3'
	uci set advancedplus.@basic[0].primary_rgbs='225,112,88'
 	[ $mode = dark ] && uci set advancedplus.@basic[0].primary_body='#212d3c' || uci set advancedplus.@basic[0].primary_body='#f8f8f8'
fi
if [ "x$(uci -q get advancedplus.@basic[0].fontmode)" = "x1" ] ; then
	uci set advancedplus.@basic[0].font_d='1.4rem'
	uci set advancedplus.@basic[0].font_z='1.1rem'
	uci set advancedplus.@basic[0].font_x='1rem'
else
	uci set advancedplus.@basic[0].font_d='1.2rem'
	uci set advancedplus.@basic[0].font_z='0.92rem'
	uci set advancedplus.@basic[0].font_x='0.875rem'
fi
uci commit advancedplus
}

start() {
    [ -f /etc/config/advancedplus ] || reset  
    kucatset
    rm -rf /tmp/luci*
}

stop() {
rm -rf /tmp/luci*
}