name: Sync Multiple Repos
on:
  schedule:
    - cron: '0 0 * * *'  # 每天同步一次
  workflow_dispatch:      # 手动触发
  
jobs:
  sync:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: 
          # sirpdboy 的仓库
          - { url: "https://github.com/sirpdboy/luci-app-advancedplus.git", dir: "luci-app-advancedplus", dest: "advancedplus", branch: "main" }
          - { url: "https://github.com/sirpdboy/luci-theme-kucat.git", dir: "luci-theme-kucat", dest: "kucat", branch: "js" }
          - { url: "https://github.com/sirpdboy/luci-app-netwizard.git", dir: "luci-app-netwizard", dest: "netwizard", branch: "main" }
          - { url: "https://github.com/sirpdboy/luci-app-netspeedtest.git", dir: "luci-app-netspeedtest", dest: "netspeedtest", branch: "js" }
          - { url: "https://github.com/sirpdboy/luci-app-netdata.git", dir: "luci-app-netdata", dest: "netdata", branch: "master" }
          - { url: "https://github.com/sirpdboy/luci-app-timecontrol.git", dir: "luci-app-nft-timecontrol", dest: "timecontrol", branch: "main" }
          - { url: "https://github.com/sirpdboy/luci-app-taskplan.git", dir: "luci-app-taskplan", dest: "taskplan", branch: "master" }
          - { url: "https://github.com/sirpdboy/luci-app-poweroffdevice.git", dir: "luci-app-poweroffdevice", dest: "poweroffdevice", branch: "js" }
          # 其他仓库
          - { url: "https://github.com/linkease/istore.git", dir: "luci", dest: "store", branch: "main" }
          - { url: "https://github.com/linkease/istore.git", dir: "translations", dest: "store", branch: "main" }
          - { url: "https://github.com/tty228/luci-app-wechatpush.git", dir: "luci-app-wechatpush", dest: "wechatpush", branch: "master" }
          - { url: "https://github.com/gdy666/luci-app-lucky.git", dir: "luci-app-lucky", dest: "lucky", branch: "main" }
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整历史记录
      
      - name: Sync ${{ matrix.repo.dir }}
        run: |
          echo "▶️ 开始同步 ${{ matrix.repo.url }} (分支: ${{ matrix.repo.branch }})"
          
          # 尝试克隆指定分支，失败则尝试其他可能分支
          if ! git clone --filter=blob:none --no-checkout --branch ${{ matrix.repo.branch }} ${{ matrix.repo.url }} src_repo 2>/dev/null; then
            echo "⚠️ 分支 ${{ matrix.repo.branch }} 不存在，尝试默认分支..."
            git clone --filter=blob:none --no-checkout ${{ matrix.repo.url }} src_repo
            cd src_repo
            DEFAULT_BRANCH=$(git symbolic-ref --short refs/remotes/origin/HEAD | cut -d'/' -f3)
            git checkout $DEFAULT_BRANCH
          else
            cd src_repo
            git checkout ${{ matrix.repo.branch }}
          fi
          
          # 设置稀疏检出
          git sparse-checkout init --cone
          echo "${{ matrix.repo.dir }}" > .git/info/sparse-checkout
          
          # 复制文件
          mkdir -p ../${{ matrix.repo.dest }}
          if [ -d "${{ matrix.repo.dir }}" ]; then
            cp -r ${{ matrix.repo.dir }}/* ../${{ matrix.repo.dest }}/
          else
            echo "❌ 目录 ${{ matrix.repo.dir }} 不存在"
            exit 1
          fi
          
          cd ..
          rm -rf src_repo
          echo "✅ 同步完成"
        continue-on-error: true  # 单个仓库失败不影响其他任务

      - name: Commit and Push Changes
        if: matrix.repo.dir == 'luci-app-lucky'  # 只在最后一个任务提交
        run: |
          # 设置Git身份
          git config --global user.name "zxmlysxl"
          git config --global user.email "zxmlysxl@gmail.com"
          
          # 添加所有变更
          git add .
          
          # 生成简化的提交信息
          COMMIT_MSG="Sync: "
          COMMIT_MSG+="advancedplus, kucat, netwizard, netspeedtest, "
          COMMIT_MSG+="netdata, timecontrol, taskplan, poweroffdevice, "
          COMMIT_MSG+="store, wechatpush, lucky"
          
          # 提交并推送
          git commit -m "$COMMIT_MSG"
          git push
