name: Sync Multiple Repos
on:
  schedule:
    - cron: '0 0 * * *'  # 每天同步一次
  workflow_dispatch:      # 手动触发
  
jobs:
  sync:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: 
          - { url: "https://github.com/sirpdboy/luci-app-advancedplus.git", dir: "luci-app-advancedplus", dest: "advancedplus" }
          - { url: "https://github.com/sirpdboy/luci-theme-kucat.git", dir: "luci-theme-kucat", dest: "kucat" }
          - { url: "https://github.com/sirpdboy/luci-app-netwizard.git", dir: "luci-app-netwizard", dest: "netwizard" }
          - { url: "https://github.com/sirpdboy/luci-app-netspeedtest.git", dir: "luci-app-netspeedtest", dest: "netspeedtest" }
          - { url: "https://github.com/sirpdboy/luci-app-netdata.git", dir: "luci-app-netdata", dest: "netdata" }
          - { url: "https://github.com/sirpdboy/luci-app-timecontrol.git", dir: "luci-app-nft-timecontrol", dest: "timecontrol" }
          - { url: "https://github.com/sirpdboy/luci-app-taskplan.git", dir: "luci-app-taskplan", dest: "taskplan" }
          - { url: "https://github.com/sirpdboy/luci-app-poweroffdevice.git", dir: "luci-app-poweroffdevice", dest: "poweroffdevice" }
          - { url: "https://github.com/linkease/istore.git", dir: "luci-app-store",  dest: "store" }
          - { url: "https://github.com/tty228/luci-app-wechatpush.git", dir: "luci-app-wechatpush", dest: "wechatpush" }
          - { url: "https://github.com/gdy666/luci-app-lucky.git", dir: "luci-app-lucky", dest: "lucky" }
    steps:
      - uses: actions/checkout@v4
      - run: |  
          git clone --filter=blob:none --no-checkout ${{ matrix.repo.url }} src_repo
          cd src_repo
          git sparse-checkout set ${{ matrix.repo.dir }}
          git checkout main
          cp -r ${{ matrix.repo.dir }} ../${{ matrix.repo.dest }}
          cd ..
          rm -rf src_repo
      - name: Commit and Push
        if: matrix.repo.dir == 'luci-app-lucky'  
        run: |
          git config --global user.name "zxmlysxl"
          git config --global user.email "zxmlysxl@gmail.com"
          git add .
          git commit -m "Sync: ${{ join(matrix.repo.*, ', ') }}"
          git push
